@startuml
class Persona {
    - nombre: String
    - apellidos: String
    - añoNacimiento: int
    
    + Persona()
    + Persona(nombre: String, apellidos: String, añoNacimiento: int)
    + getEdad(añoActual: int): int
    + setName(nombre: String): void
    + getName(): String
    + setLastname(apellidos: String): void
    + getLastname(): String
    + setBirthyear(año: int): void
    + getBirthyear(): int
}
@enduml
